### ISSUE TITLE
Setting a text field and then setting it to empty

### ISSUE THREAD

**Issue by omaxmedia90** [contentful/contentful.objc#16]
Adding text to a text field in contentful, and then setting it to empty, should result in getting a nil value in objective-c.

example:

in objective-c, an empty text fields results in nil
set the textfield to have text, in the contentful admin.
in objective-c, the field has the proper string value
set the textfield to have no text, in contentful admin
in objective-c, the field should be nil again, but has a string value of @""

seems like a bug.

**Comment by neonichu** [comment]
Closing this, as it is not actionable here.
