### ISSUE TITLE
Problem instantiating CDAContentType on space migrated from StorageRoom.

### ISSUE THREAD

**Issue by AdrianFerreyra** [contentful/contentful.objc#25]
I've migrated from StorageRoom to Contentful, using the tools provided by the first to do so. Now, when I try to use contentful's delivery API for Obj-C, I get an exception when initializing the CDAFields of a CDAContentType object.

![screen shot 2015-01-13 at 12 47 00](https://cloud.githubusercontent.com/assets/4059729/5723382/6a89f90a-9b22-11e4-9485-bcf479beb6bc.png)
![screen shot 2015-01-13 at 12 47 55](https://cloud.githubusercontent.com/assets/4059729/5723383/6d20777a-9b22-11e4-8189-af9dbd4266b3.png)

Can you please tell me how can I adjust my content types to make it work?

thanks!

**Comment by neonichu** [comment]
I think this is related to the bug fixed in 54578dda12624e8f853ce764c44717b1f14623a3.

There hasn't been a new release including this fix, could you try this out by changing your Podfile to:

```
pod 'ContentfulDeliveryAPI', :head
```

and doing a `pod install`

**Comment by AdrianFerreyra** [comment]
Thank you so much for your response!

**Comment by neonichu** [comment]
Great that it works - since this seems to be a somewhat common issue, I'll cut a new point-release of the SDK, then you'll be able to move off `:head` again.

**Comment by neonichu** [comment]
Fix is included in the just released version 1.4.8: <https://github.com/contentful/contentful.objc/releases/tag/1.4.8>
