### ISSUE TITLE
invalid CDAAsset URL

### ISSUE THREAD

**Issue by jameshays** [contentful/contentful.objc#26]
There are times when the weak client reference in a CDAAsset will be nil.  It appears that there is limited (but important) usage of self.client in the asset, but would it be possible or warranted for the URL to be created when the Object is created so that it is not dependent on client.  When client is nil for whatever reason, the URL schema comes back as (null):// which is then invalid.

**Comment by neonichu** [comment]
Good catch, it would make sense to query the protocol during object creation, so that the client is not needed for this anymore.

**Comment by jameshays** [comment]
Or make the client a strong reference, but I can see your reasonings for not doing this as well.

**Comment by jameshays** [comment]
When will this fix be in the updated podspec?

**Comment by neonichu** [comment]
The change is available in 1.4.9 which was just released: <https://github.com/contentful/contentful.objc/releases/tag/1.4.9> 

BTW, as we aim to always keep master stable, you can also use `:head` or `:commit` in your Podfile to temporarily switch to not yet released code.
