### ISSUE TITLE
Object fields are not returned

### ISSUE THREAD

**Issue by yood** [contentful/contentful.objc#27]
I have a content type with an Object field (arbitrary JSON).

However, when I fetch an entry of that content type, it doesn't return that Object field at all.

I went down to curl and found that that field wasn't returned at all.

`curl -X GET -H 'Authorization: Bearer <token>' https://cdn.contentful.com/spaces/space-id/entries/entry-id`

Can you add support for fetching fields of type Object?

Daniel

**Comment by yood** [comment]
I called the management API instead and there, it returned the field of type Object.

Is this by design? If so, please update the documentation!

**Comment by neonichu** [comment]
Is this an unpublished change by any chance? The CDA will only return the published state of resources, while the CMA will also return not yet published content.

**Comment by yood** [comment]
It was unpublished, sorry!
