### ISSUE TITLE
Entries loose all assets when using the sync API

### ISSUE THREAD

**Issue by hanneskl** [contentful/contentful.objc#28]

**Comment by neonichu** [comment]
Could you elaborate a bit on how you use the sync API in order to see this issue?

Ideally, please also share your space credentials with us via support@contentful.com - thanks!

**Comment by hanneskl** [comment]
I used to use fetchEntriesMatching
and everything was working fine.

I switched to initialSynchronizationWithSuccess
but now all CDAAssets in my  CGAEntries are nil.

I checked the original data coming over http and the assets are included
there.

**Comment by neonichu** [comment]
Fixed in a8e4480b2a9af79ccbfa703075392c61dd4f961a

For the meantime, you can use:

```
pod 'ContentfulDeliveryAPI', :head
```

to use this fix - it will be included in the next release of the SDK as well.
