### ISSUE TITLE
Support for AFNetworking 3

### ISSUE THREAD

**Issue by neonichu** [contentful/contentful.objc#47]
Eventually, people will be migrating to AFNetworking 3 for their apps, leading to a conflict with the CDA SDK, especially when using CocoaPods. We should start a 2.0 branch which moves away from AFNetworking 2.x for midterm evolution. Another option would be to move people over to [contentful.swift](https://github.com/contentful/contentful.swift).

**Comment by neonichu** [comment]
Main obstacle going AFNetworking 3.0 is that the `NSURLConnection` based API is gone, so is support for iOS 6.

**Comment by dmorrow** [comment]
@neonichu Any thoughts on this migration or contentful.swift supporting CoreData persistence?  We have other dependancies that have started requiring AFNetworking 3, so we are stuck using older versions and missing out on fixes.

**Comment by mrrobby** [comment]
I'd be in favor of moving to `AFNetworking ~> 3.0`.  `NSURLConnection` is getting a lot of deprecation too so I believe that to be a weighting factor.  Apple reports less than 5% of devices are using `iOS < 8.0` too.  If you do migrate, one feature request would be to expose the AFSecurityPolicy through the client (or configuration) so we can at least pin to the root CA.  We'd be happy to help out if needed.  It would solve some issues for us too.  Also on the note about moving people to contentful.swift, [Swift 3.0 will also have code breaking changes](https://github.com/apple/swift-evolution#development-major-version--swift-30).

**Comment by neonichu** [comment]
Yah, this should definitely happen at some point. There's an unfinished branch at <https://github.com/contentful/contentful.objc/tree/2.0-dev> which is now quite out of date in regards to `master`.

Regarding `contentful.swift`, there is <https://github.com/contentful/contentful-persistence.swift> now, albeit it is still a bit in its early stages.

**Comment by neonichu** [comment]
Brought the branch up to date with current `master`, but the full test suite isn't running, yet. However, it should be fine for testing it if you urgently need to switch to AFNetworking 3:

```ruby
pod 'ContentfulDeliveryAPI', :git => 'https://github.com/contentful/contentful.objc', :branch => '2.0-dev'
```

**Comment by mrrobby** [comment]
Awesome!  Thanks @neonichu.  Is there an open issue for setting the security policy for pinning to the root CA as an option?  You're API is put together well in that it could be exposed easily, maybe as part of the `CDAConfiguration`.  Would you see any concerns in doing that?

**Comment by neonichu** [comment]
@mrrobby don't see any concerns, could you open an issue for it? Thanks 👍

**Comment by mrrobby** [comment]
You got it.  See #53

**Comment by CrazyPro007** [comment]
Hello neonichu,

Please let me know asap that the stable branch having support for AFNetworking 3.0 in objective c is exist or not. 
If exist than please provide me the pod setup path as i am using this path (pod 'ContentfulDeliveryAPI', :git => 'https://github.com/contentful/contentful.objc', :branch => '2.0-dev') and it giving error while installing.

Its urgent.

**Comment by neonichu** [comment]
@CrazyPro007 could you please share which errors you're seeing? 

This branch should be stable, there are just some smaller issues with the test suite which haven't been resolved, yet and those block merging this to `master`.

**Comment by mrrobby** [comment]
@CrazyPro007, what version of CocoaPods are you running?  The lock file is showing an older version so if you are on 1.0, maybe try switching to 0.38.2 and try again.

**Comment by CrazyPro007** [comment]
@neonichu i am using cocoapods version 1.0 and troubling with  following errors. 

[!] Error installing ContentfulDeliveryAPI
[!] /usr/bin/git clone https://github.com/contentful/	contentful.objc /var/folders/m6/fp4xfrdx5mx7y0gryyw_ryym0000gn/T/d20160808-22421-17nowla --template= --single-branch --depth 1 --branch 2.0-dev

Cloning into '/var/folders/m6/fp4xfrdx5mx7y0gryyw_ryym0000gn/T/d20160808-22421-17nowla'...
fatal: unable to access 'https://github.com/contentful/	contentful.objc/': The requested URL returned error: 400

**Comment by neonichu** [comment]
@CrazyPro007 that error looks like there is a problem with your connection to GitHub rather than with the branch — are you able to successfully clone other branches of the same repo?

**Comment by CrazyPro007** [comment]
@neonichu 

I am successfully able to clone the other branches from github and even your branch #pod 'ContentfulDeliveryAPI'

**Comment by neonichu** [comment]
@CrazyPro007 can you share your Podfile please, I'm unfortunately not able to reproduce this

**Comment by CrazyPro007** [comment]
@neonichu 
Pod file unable to upload so i am uploading the pdf file.


[Podfile.pdf](https://github.com/contentful/contentful.objc/files/406541/Podfile.pdf)

**Comment by neonichu** [comment]
Looks like there are some accidental extra characters in the repo URL, please try this Podfile instead:

```ruby
target 'Contentful' do
  pod 'ContentfulDeliveryAPI', :git => 'https://github.com/contentful/contentful.objc', :branch => '2.0-dev'

target 'ContentfulTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'ContentfulUITests' do
  inherit! :search_paths
  # Pods for testing
end

end
```

**Comment by CrazyPro007** [comment]
Thanks @neonichu 
It working fine now.

**Comment by loudmouth** [comment]
Support for AFNetworking 3 has been moved to a new branch: #67
