### ISSUE TITLE
Crash when returning from background during performSynchronization()

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful.objc#49]
We are using CoreDataManager.performSynchronizationWithSuccess, failure and some of our testers are getting a crash when we put the app into the background and then bring it forward during sync.
Its not generating any crash logs, so its a bit tough to share more details

**Comment by neonichu** [comment]
I'm thinking the most probable cause is a Core Data concurrency issue, you could try running the app from Xcode using `-com.apple.CoreData.ConcurrencyDebug 1` as a launch argument and see if something turns up.

**Comment by dmorrow** [comment]
Turns out this was not a crash at all, but rather a delay due to extended processing that we were doing in CoreData in `applicationWillEnterForegroundNotification`.  On older devices, this processing didn't complete in enough time, so the app didn't return to the foreground.  As a result the app was getting shut down with ```Exception Codes: 0x000000008badf00d
Exception Note:  SIMULATED (this is NOT a crash)```
