### ISSUE TITLE
Transparent images with offline caching

### ISSUE THREAD

**Issue by M2Bas** [contentful/contentful.objc#54]
When using the build in UIImageView+CDAAsset extension to display images and use it's internal offline caching ,`offlineCaching_cda` set to `YES`. All images that have transparency will have a black background instead of the transparency. 

This is caused by the following line : 
https://github.com/contentful/contentful.objc/blob/master/Code/UIKit/UIImageView%2BCDAAsset.m#L86

As stated in the documentation of : `UIGraphicsBeginImageContextWithOptions`
The opaque parameter should be set to `NO`, to support images with transparency. Instead of the hardcoded `YES` right now.

This change will cause the bitmap storage to increase as said in the same documentation.
If this is set to `YES` for a reason, I would like to recommend a setting to allow it anyway. Just like the `offlineCaching_cda`. Allowing the developer to choose what fits best for him/her.

If it isn't, I would like to request the default value to be set to `NO` to support transparent images with your build in offline caching.

**Comment by neonichu** [comment]
Total oversight, I'll change the setting in the next release
