### ISSUE TITLE
Empty pod when running Pod Update

### ISSUE THREAD

**Issue by Conrad-m-wise** [contentful/contentful.objc#57]
Hi,

I am getting an empty pod when i run pod update with -> pod 'ContentfulDeliveryAPI', '1.10.2' or pod 'ContentfulDeliveryAPI', '1.10.3'. If i set the version to pod 'ContentfulDeliveryAPI', '1.10.1' i get the source files.

**Comment by neonichu** [comment]
That's quite strange, I can't see any issues with those tags — could you try running `pod cache clean` and retry?

**Comment by Conrad-m-wise** [comment]
Fixed it thanks.
