### ISSUE TITLE
Not able to run project. Some files missing.

### ISSUE THREAD

**Issue by arpanCode** [contentful/contentful.objc#58]
At first Pods are empty.Once i fixed that by creating new pod file. Then Some files are missing Can you help me ?

**Comment by neonichu** [comment]
Did you also fetch the submodules? You can do so by either doing `git clone --recursive` or `git submodule update --init` after the fact.

**Comment by arpanCode** [comment]
Thanks neo ! For quick reply.
 Done. But now pods are not installing. Podfile have some unexpected syntax errors .

**Comment by neonichu** [comment]
Please run

```
bundle install
bundle exec pod install
```

to make sure you're using the correct version of CocoaPods.

**Comment by arpanCode** [comment]
@neonichu 
Can you please help me to get access_token. I am going through the my account i am able to get api keys/ space key but where i can find  access_token ??

**Comment by neonichu** [comment]
API key and access token are basically the same thing.

**Comment by arpanCode** [comment]
Okay. Thanks Neo !
