### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful.objc#81]
The tvOS branch hasn't been updated in a number of years.  Is there any update on tvOS support?

**Comment by loudmouth** [comment]
Hi @dmorrow thanks for bringing this up. I'd recommend using [contentful.swift](https://github.com/contentful/contentful.swift) for tvOS projects. Version [0.4.0-beta2](https://github.com/contentful/contentful.swift/releases/tag/0.4.0-beta2) implements all the same features that this repo does and so far I haven't heard of any issues that would raise concern. It is installable for tvOS via both carthage and cocoapods.

After there is also a management SDK in swift, the objective-c tooling will be deprecated.

Let me know if you have further questions.

**Comment by loudmouth** [comment]
That being said, if you already have a project using this SDK that runs on iOS, I can consider moving tvOS support up higher in priority.

**Comment by dmorrow** [comment]
Thanks @loudmouth - we currently have an iOS project in Swift which uses the objc versions of the SDK and persistence.  Except for the management portion, is there anything else missing between these two libraries?  We don't need management features.

**Comment by loudmouth** [comment]
The main thing missing from the Swift SDK is a Swifty API to communicate with Contentful's images API. This is on the roadmap to be implemented and hopefully will be out in the next 2 months.

**Comment by loudmouth** [comment]
@dmorrow any updates?

Looking to close this ticket if everything is OK on your end.

**Comment by paywithextend** [comment]
I think we're fine for now - will give a shout with any issues.

**Comment by dmorrow** [comment]
I think we're fine for now - will give a shout with any issues.

**Comment by loudmouth** [comment]
Thanks. Closing for now. Happy coding :-)
