### ISSUE TITLE
Failing to compile on iOS 11 simulators Xcode 9

### ISSUE THREAD

**Issue by evanhughes3** [contentful/contentful.objc#90]
Hello.  I am using v2.0.3 of `ContentfulDeliveryAPI` pod, and am getting a build error when trying to build on iOS 11 simulators.  I just updated Xcode to test on iOS 11.

Error is happening here:
https://github.com/contentful/contentful.objc/blob/master/ContentfulDeliveryAPI/Resources/CDAEntry.h#L12

Error message: `Error:(12, 24) expected "FILENAME" or <FILENAME>`

Is there a reason why it was reverted from `#import <MapKit/MapKit.h>`? That seems to get it compiling.

Thanks!

**Comment by loudmouth** [comment]
Hmm... not sure how this got merged. Thanks for opening the issue. Will have a fix out asap.

**Comment by loudmouth** [comment]
@evanhughes3 could you check out [this branch](https://github.com/contentful/contentful.objc/pull/91) and let me know if everything is working for you?

**Comment by evanhughes3** [comment]
Yes that did fix it! Thanks for the quick reply.

What I am not sure about is why `__has_feature(modules)` is false for this particular pod.  And it only seems to happen when running my "Specs" target.  When I run my App target, it worked even before your fix, meaning it was loading the `@import MapKit;`  I'm starting to wonder if something got funny in my target configuration, and that this is not necessarily a breaking change on your side.

In my podfile I have `use_frameworks!`, and in my Pods Project -> Build Settings, "Enable Modules (C and Objective-C)" is set to "Yes." Do you have any idea what might be going on?

**Comment by loudmouth** [comment]
I see. Regardless of if there is an issue with your specs target, there certainly were compilation issues with Xcode 9 that had to be fixed. I'm going to merge those changes, but leave this issue open for now. Would you be willing to provide an update when you find out what is causing your target to compile without module support?

**Comment by evanhughes3** [comment]
Ok sounds good.  Yes, if I figure it out I'll leave a follow up comment here.  Thanks!

**Comment by Sethmr** [comment]
The pod ObjectMapper that is being used by you has a Swift 4 version available, but the version you are using is 2.2.9... Could you fix this so that Swift 4 projects can build?

**Comment by loudmouth** [comment]
Hi @Sethmr I think you want to be opening an issue at [contentful.swift](https://github.com/contentful/contentful.swift) as this is the objective-c sdk. 

Swift 4 projects should be building with contentful.swift anyway as you can use Swift 3.2 frameworks in swift 4 projects. Moving to Swift 4 is a firm decision to break backwards compatibility with those using Xcode 8 still. It likely won't happen for another month.
