### ISSUE TITLE
Adding as a development pod throws error due to podspec file

### ISSUE THREAD

**Issue by jackdewhurst** [contentful/contentful.objc#92]
Hi,

I'm trying to add ContentfulDeliveryAPI as a development cocoapod but It fails to install when running `pod install` due to the following error:

[!] Failed to load 'ContentfulDeliveryAPI' podspec: 
[!] Invalid ContentfulDeliveryAPI.podspec file: cannot load such file -- dotenv/load.
--
The offending line in podspec is: 
  
 >  require 'dotenv/load'
   

I've tried adding `.env` from the project to the same directory but it didn't fix the issue.. Has anyone had any luck with this?

**Comment by jackdewhurst** [comment]
Ok I've fixed it by editing the podspec and removing the requirement for `.env`, then manually entering the sdk version number in line '`s.version`

Closing the issue.

**Comment by loudmouth** [comment]
@jackdewhurst you can run bundle install inside the Contentful project directory and that should also solve it

**Comment by loudmouth** [comment]
@jackdewhurst just a quick correction for my earlier comment: the proper solution is to add

```ruby
gem 'dotenv'
gem 'cocoapods'
```

to your Gemfile and use `bundle exec pod install` as opposed to a regular `pod install` if you plan on using development branches of contentful.

**Comment by anuChandra-dev** [comment]
Hi, I am facing the same issue. Didn't find the solution. Can anyone help me out.
[!] Failed to load 'Contentful' podspec: 
[!] Invalid `Contentful.podspec` file: cannot load such file -- dotenv/load.
