### ISSUE TITLE
Unknown type CDAResponse

### ISSUE THREAD

**Issue by wmcbruce** [contentful/contentful.objc#93]
Trying to integrate the CMA framework into a test project and I get unknown type errors for CDAResponse.

Using a very simple project pulling the content management api in via pods.  

What am I missing?

**Comment by loudmouth** [comment]
Hi @wmcbruce 

I just fired up a new project with Xcode 9 and was able to successfully install the SDK and compile.
I'm using Cocoapods 1.3.1 via the Ruby Bundler, and therefore running the following command to install the Management API pod.

```bash
bundle exec pod install
```

Here is the Podfile:

```ruby
#!/usr/bin/ruby

use_frameworks!
platform :ios, "8.0"

target 'TestPodInstall' do
  pod 'ContentfulManagementAPI', '~> 0.10.1'
end
```

Are you attempting to use different versions than I have specified? I highly recommend the latest version of the CMA SDK: `0.10.1`

**Comment by loudmouth** [comment]
Closing do to inactivity. Also note the deprecation plan for the 'ContentfulManagementAPI'—to be deprecated July 13, 2018. See: #95
